### ISSUE TITLE
Invoice app 

### ISSUE THREAD

**Issue by yamamoto-tsunetomo** [yamamoto-tsunetomo/MediAdmin#65]
- [x] - User Authentication
- [x]  Invoice Creation
- [x] #66
- [x] Automated Numbering
- [x] Client Management
- [x]  Itemized Billing
- [x]  Tax Calculation
- [ ]  Discounts and Coupons
- [ ]  Due Dates and Payment Terms
- [ ]  Invoice Status Tracking
- [ ]  Payment Gateway Integration
- [ ]  Partial Payments
- [x] Invoice History and Archiving
- [ ] Invoice Reminders
- [x] Attachment Support
- [ ] Reporting and Analytics
- [ ] Customizable Permissions

- [x] Create a new Django app named "invoices".
- [x] Define models for invoices, including fields like invoice number, reception ID, date, total amount, payment status, etc.
- [x] Set up database relationships between invoices and receptions.
- [x] Implement CRUD functionality for invoices (Create, Read, Update, Delete).
- [x] Create a form for adding new invoices, including validation for required fields.
- [x] Implement a view to display a list of invoices.
- [x] Include pagination for the invoice list view if there are many invoices.
- [x] Implement a detail view to display individual invoice details.
- [x] Add search and filter functionality to the invoice list view.
- [ ] Implement a feature to generate PDF invoices for easy printing and sharing.
- [ ] Add functionality to mark invoices as paid or unpaid.
- [ ] #70
- [ ] Allow users to export invoice data to CSV or Excel files.
- [ ] Implement email notifications for sending invoices to patients or clients.
- [ ] Include settings for configuring invoice number formats and invoice settings.
- [ ] Add permissions and access control to restrict invoice management to authorized users.
- [ ] Implement error handling and validation for invoice forms.
- [x] Create templates for displaying invoice details and the invoice list.
- [ ] Implement unit tests to ensure the reliability of invoice-related functionality.
- [ ] Integrate the invoice app with other parts of the clinic management system, such as receptions and appointments, to ensure data consistency and coherence.

**Comment by hoseynchegeni** [comment]
پشتیبانی از ارز و زبان: پشتیبانی از چندین واحد پولی و زبانی را برای پاسخگویی به مشتریان بین المللی ارائه می دهد.
