### ISSUE TITLE
Doctor Managment

### ISSUE THREAD

**Issue by yamamoto-tsunetomo** [yamamoto-tsunetomo/MediAdmin#73]
- [x] 1. Doctor Profile Management
- [x] 2. Appointment Scheduling
- [x] 3. Patient Record Access
- [ ] #81
- [x] 7. Billing and Invoicing
- [x] #82 (In progress in #89 )
- [ ] 10. Reporting and Analytics ( In Progress in #75 )
- [x]  Template
- [ ] Chat app

**Comment by hoseynchegeni** [comment]
ابزارهای ارتباطی: ابزارهای ارتباطی مانند پیام‌رسانی امن، تماس‌های ویدیویی و یکپارچه‌سازی ایمیل را برای ارتباط بی‌وقفه با بیماران، همکاران و کارکنان ارائه می‌دهد.
